cursor #2a2a2a
cursor_text_color #424242

foreground            #2a2a2a
background            #ffffff
selection_foreground  #ffffff
selection_background  #4a4d56
url_color             #2b303c

color0   #2a2a2a
color1   #793044
color2   #215f2a
color3   #999326
color4   #2c313f
color5   #60636a
color6   #2b303c
color7   #222223
color8   #6e6f71
color9   #b26377
color10  #3f8c4a
color11  #a5a031
color12  #747a8c
color13  #60636a
color14  #42464e
color15  #bbbcbf
